name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install SSH key
        run: |
          echo "${{ secrets.EC2_PEM_KEY }}" | tr -d '\r' > bookleum.pem
          chmod 400 bookleum.pem

      - name: Verify SSH key creation
        run: ls -l bookleum.pem

      - name: Deploy to EC2
        run: |
          ssh -vvv -i bookleum.pem -o StrictHostKeyChecking=no ubuntu@ec2-13.125.139.233.ap-northeast-2.compute.amazonaws.com 'cd BookLeum/Front/bookleum && git pull origin main && npm install && npm run build && pm2 restart all'
